# Generated by Django 4.2.6 on 2023-10-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForMySQL',
            fields=[
                ('mysql_field1', models.CharField(max_length=100)),
                ('mysql_field2', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelForSQLite',
            fields=[
                ('sqlite_field1', models.CharField(max_length=100)),
                ('sqlite_field2', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
