# Generated by Django 4.2.6 on 2023-10-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelForMySQL',
        ),
        migrations.DeleteModel(
            name='ModelForSQLite',
        ),
    ]
