# Generated by Django 4.2.6 on 2023-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allocation', models.IntegerField(blank=True, null=True)),
                ('connect_percentage', models.FloatField(blank=True, null=True)),
                ('paid_count', models.IntegerField(blank=True, null=True)),
                ('resolution_percentage', models.FloatField(blank=True, null=True)),
                ('avg_attempt_intensity', models.FloatField(blank=True, null=True)),
                ('avg_connect_intensity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Card_data',
                'managed': False,
            },
        ),
    ]
