# Generated by Django 4.2.6 on 2023-10-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_card_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_data',
            options={},
        ),
    ]
