# Generated by Django 4.2.6 on 2023-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0005_alter_card_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_data',
            options={'managed': True},
        ),
    ]
