# Generated by Django 4.2.6 on 2023-10-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0006_alter_card_data_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect_by_Month',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Month', models.CharField(blank=True, max_length=255, null=True)),
                ('Connect_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Connect_by_Month',
                'managed': True,
            },
        ),
    ]
