# Generated by Django 4.2.6 on 2023-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0009_alter_connect_by_month_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect_by_month',
            options={'managed': True},
        ),
    ]
