# Generated by Django 4.2.6 on 2023-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0011_alter_connect_by_month_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=30, null=True)),
                ('data_validation', models.CharField(blank=True, max_length=30, null=True)),
                ('phone1', models.CharField(blank=True, max_length=30, null=True)),
                ('emi_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('pos', models.CharField(blank=True, max_length=30, null=True)),
                ('cyle_date', models.CharField(blank=True, max_length=30, null=True)),
                ('due_date', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.CharField(blank=True, max_length=30, null=True)),
                ('zone', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('finl_risk', models.CharField(blank=True, max_length=30, null=True)),
                ('language_1', models.CharField(blank=True, max_length=30, null=True)),
                ('language_2', models.CharField(blank=True, max_length=30, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('callstatus', models.CharField(blank=True, max_length=30, null=True)),
                ('finalstatus', models.CharField(blank=True, max_length=30, null=True)),
                ('finalcallduration', models.CharField(blank=True, max_length=30, null=True)),
                ('noofattempt', models.CharField(blank=True, max_length=30, null=True)),
                ('noofconnect', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_status', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=30, null=True)),
                ('allocation_date', models.CharField(blank=True, max_length=30, null=True)),
                ('month', models.CharField(blank=True, max_length=30, null=True)),
                ('product_sort', models.CharField(blank=True, db_column='PRODUCT Sort', max_length=30, null=True)),
                ('product_type', models.CharField(blank=True, db_column='PRODUCT TYPE', max_length=30, null=True)),
                ('sub_product', models.CharField(blank=True, db_column='Sub Product', max_length=30, null=True)),
            ],
            options={
                'db_table': 'my_table',
                'managed': False,
            },
        ),
    ]
