# Generated by Django 4.2.6 on 2023-10-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0012_my_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_table',
            options={'managed': True},
        ),
    ]
